name: djangomatplotlib
dependencies:
  - python=3.10
  - pip
  - pip:
      - django==4.0.5
      - djangorestframework==3.13.1
      - djangorestframework-simplejwt==4.8.0
      - drf-yasg==1.20.0
      - gunicorn==20.1.0
      - flake8==4.0.1
      - pillow==9.1.1
      - pyjwt==2.4.0
      - django-cors-headers==3.13.0
      - apscheduler==3.8.1
      - djoser==2.1.0
      - psycopg2-binary==2.9.2
      - psycopg2==2.9.3