# Generated by Django 3.2.8 on 2022-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartjs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social972',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthyear', models.CharField(choices=[(1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983')], default=1980, max_length=4)),
                ('zipcode', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
